FROM python:3.13-slim-buster

WORKDIR /app

ADD . /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8503

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=http://10.200.31.212:8503"]